name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Checking Code style
        run: sbt check

      - name: Build and Publish to Local
        run: sbt +publishLocal
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Run Test
        if: success() || failure()
        run: sbt coverage test coverageReport

      - name: Aggregate coverage report
        if: success() || failure()
        run: sbt coverageAggregate

      - name: Upload test coverage report
        if: success() || failure()
        run: bash <(curl -s https://codecov.io/bash)
        
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}   

  ci:
    runs-on: ubuntu-20.04
    needs: [ build, test ]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"